# Generated by Django 4.2.13 on 2025-10-17 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_formstate_cognito_save_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SymposiumRegistration',
            new_name='EventRegistrations',
        ),
    ]
