# Generated by Django 4.2.13 on 2025-10-17 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_rename_symposiumregistration_eventregistrations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SymposiumDelegate',
            new_name='EventDelegate',
        ),
        migrations.RenameModel(
            old_name='EventRegistrations',
            new_name='EventRegistration',
        ),
    ]
