# Generated by Django 4.2.13 on 2025-10-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_registrationlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormState',
        ),
    ]
