# Generated by Django 4.2.13 on 2025-10-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_delete_formstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationlink',
            name='email',
        ),
        migrations.AddField(
            model_name='registrationlink',
            name='user',
            field=models.CharField(default='user', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
